# Generated by Django 5.0 on 2023-12-06 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('chairsonly', models.IntegerField()),
                ('roundtable', models.IntegerField()),
                ('studenttable', models.IntegerField()),
                ('pshape', models.IntegerField()),
            ],
            options={
                'db_table': 'halls',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('balconies', models.IntegerField(blank=True, null=True)),
                ('adults', models.IntegerField(blank=True, null=True)),
                ('children', models.IntegerField(blank=True, null=True)),
                ('haswifi', models.BooleanField(blank=True, null=True)),
                ('hastv', models.BooleanField(blank=True, null=True)),
                ('hasminibar', models.BooleanField(blank=True, null=True)),
                ('hasac', models.BooleanField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.CreateModel(
            name='HallBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_number', models.CharField(max_length=15)),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.hall')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.user')),
            ],
            options={
                'db_table': 'hall_booking',
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_number', models.CharField(max_length=15)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.user')),
            ],
            options={
                'db_table': 'room_booking',
            },
        ),
    ]
